export const urlConstants ={
    GET_URL_DATA_LOADING:"GET_URL_DATA_LOADING",
    GET_URL_DATA_SUCCESS:"GET_URL_DATA_SUCCESS",
    GET_DATA_ERROR:"GET_DATA_ERROR",

    POST_URL_DATA_LOADING:"POST_URL_DATA_LOADING",
    POST_URL_DATA_SUCCESS:"POST_URL_DATA_SUCCESS",
    POST_URLDATA_ERROR:"POST_URLDATA_ERROR",

    GET_ANALYTICS_LOADING:"GET_ANALYTICS_LOADING",
    GET_ANALYTICS_SUCCESS:"GET_ANALYTICS_SUCCESS",
    GET_ANALYTICS_ERROR:"GET_ANALYTICS_ERROR",
}